# Generated by Django 4.0.6 on 2022-10-01 10:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('JOB SEEKER', 'JOB SEEKER'), ('EMPLOYER', 'EMPLOYER')], default='JOB SEEKER', max_length=200, verbose_name='role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=200)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], default='Single', max_length=200)),
                ('addressLine1', models.CharField(blank=True, max_length=200, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, choices=[('Kampala', 'Kampala'), ('Masaka', 'Masaka'), ('Mukono', 'Mukono'), ('Jinja', 'Jinja'), ('Mbarara', 'Mbarara'), ('Kabale', 'Kabale'), ('Arua', 'Arua'), ('Gulu', 'Gulu'), ('Mbale', 'Mbale'), ('Lira', 'Lira'), ('Fortportal', 'Fortportal ')], default='Kampala', max_length=200, null=True)),
                ('district', models.CharField(choices=[('Kampala', 'Kampala'), ('Masaka', 'Masaka'), ('Mukono', 'Mukono'), ('Jinja', 'Jinja'), ('Mbarara', 'Mbarara'), ('Kabale', 'Kabale'), ('Arua', 'Arua'), ('Gulu', 'Gulu'), ('Mbale', 'Mbale'), ('Lira', 'Lira'), ('Fortportal', 'Fortportal ')], default='Kampala', max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('cv', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, null=True)),
                ('position', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('experience', models.TextField()),
                ('skills', models.TextField()),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('level', models.CharField(choices=[('NQF 5 - Certificate', 'NQF 5 - UBTEB Certificate'), ('NQF 5 - Higher Certificate', 'NQF 5 - A-Level Certificate'), ('NQF 5 - Diploma', 'NQF 5 - Diploma'), ('NQF 6 - Bachelors Degree', 'NQF 6 - Bachelors Degree'), ('NQF 6 - Honours Degree', 'NQF 6 - Honours Degree'), ('NQF 6 - Postgraduate Diploma', 'NQF 6 - Postgraduate Diploma'), ('NQF 7 - Postgraduate Degree', 'NQF 7 - Postgraduate Degree'), ('NQF 7 - Masters Degree', 'NQF 7 - Masters Degree'), ('NQF 7 - Doctors Degree', 'NQF 7 - Doctors Degree')], default='NQF 5 - Certificate', max_length=200)),
                ('start_date', models.DateField()),
                ('graduated', models.DateField()),
                ('major_subject', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.resume')),
            ],
        ),
    ]
