# Generated by Django 4.0.6 on 2022-10-01 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('categoryImage', models.ImageField(default='category.png', upload_to='upload_images')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('seoDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('companyLogo', models.ImageField(default='default.png', upload_to='upload_images')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('seoDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.TextField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary', models.CharField(blank=True, max_length=1000, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('nature', models.CharField(choices=[('Full Time', 'FUll Time'), ('Part Time', 'Part TIme'), ('N/A', 'N/A'), ('Internship', 'INTERNSHIP')], default='N/A', max_length=100)),
                ('experience', models.CharField(choices=[('Less than 2yrs', 'Less than 2yrs'), ('2yrs - 5yrs', '2yrs - 5yrs'), ('5yrs -10yrs', '5yrs - 10yrs'), ('10yrs - 15yrs', '10yrs - 15yrs'), ('More than 15yrs', 'More than 15yrs'), ('N/A', 'N/A')], default='N/A', max_length=100)),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('duties', models.TextField(blank=True, null=True)),
                ('enquiries', models.TextField(blank=True, null=True)),
                ('applications', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('seoDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('urlLink', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='jobapp.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
